// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/2/6 15:51:01
const configMerger = require("D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/plugins/**/*.{js,ts,mjs}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/composables/**/*.{js,ts,mjs}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/utils/**/*.{js,ts,mjs}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["33"] = "D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp-camp/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
