// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/1/8 17:41:51
const configMerger = require("D:/Files/Desktop/summercamp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Files/Desktop/summercamp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/summercamp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/summercamp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/summercamp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/summercamp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/summercamp/plugins/**/*.{js,ts,mjs}","D:/Files/Desktop/summercamp/composables/**/*.{js,ts,mjs}","D:/Files/Desktop/summercamp/utils/**/*.{js,ts,mjs}","D:/Files/Desktop/summercamp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/summercamp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/summercamp/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["33"] = "D:/Files/Desktop/summercamp/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
